#!/usr/bin/env bash

tema="~/.config/rofi/configs.rasi"
editor="code"

configs=(
'i3'
'Polybar'
'Conky'
'LX Appearance'
'Dunst'
'Compton'
'Rofi'
'LightDM'
'qutebrowser'
'ncmpcpp'
'StartPage'
'Home'
)

res=$(printf "%s\n" "${configs[@]}" | rofi -theme "$tema" -dmenu -p "Config: " -bw 9 -lines 12 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 3)

if [ "$res" ]; then
	case $res in
		'i3') i3-msg exec $editor ~/.config/i3/config ;;
		'i3blocks')
			i3blocks=$(echo "Config;Apps" | rofi -theme "$tema" -sep ";" -dmenu -p "i3blocks" -bw 0 -lines 2 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
			if [ $i3blocks ]; then
				case $i3blocks in
					'Config') i3-msg exec $editor "${HOME}/.config/i3blocks/config" ;;
					'Apps')
						i3blocksapps=$(ls "${HOME}/.config/i3blocks/scripts/" | rofi -theme "$tema" -dmenu -p "i3 Blocks Apps" -bw 0 -lines 16 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
						if [ $i3blocksapps ]; then
							i3-msg exec $editor ~/.config/i3blocks/scripts/${i3blocksapps}
						fi
					;;
				esac
			fi
		;;
		'Polybar')
			polyconfig=$(echo "Config;Scripts;Reload" | rofi -theme "$tema" -sep ";" -dmenu -p "Polybar" -bw 0 -lines 3 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
			if [ "$polyconfig" = "Reload" ]; then
				~/.config/polybar/launch.sh
			elif [ "$polyconfig" = "Scripts" ]; then
				app=$( ls "${HOME}/.config/polybar/scripts/" | egrep ".sh|.py"  | rofi -theme "$tema" -dmenu -p "Script: " -bw 0 -lines 5 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
				if [ $app ]; then
					i3-msg exec $editor "${HOME}/.config/polybar/scripts/${app}"
				fi
			elif [ "$polyconfig" == "Config" ]; then
				i3-msg exec subl3 ${HOME}/.config/polybar/config
			fi
		;;
		'Conky') i3-msg exec $editor ~/.config/conky/conky.conf ;;
		'LX Appearance') i3-msg exec lxappearance ;;
		'Dunst')
			dunstconfig=$(echo "Config;Reload" | rofi -theme "$tema" -sep ";" -dmenu -p "Polybar" -bw 0 -lines 2 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
			if [ "$dunstconfig" = "Reload" ]; then
				killall dunst && dunst &
			elif [ $dunstconfig ]; then
				i3-msg exec $editor ~/.config/conky/conky.conf
			fi
		;;
		'Compton')
			comptonconfig=$(echo "Config;Reload" | rofi -theme "$tema" -sep ";" -dmenu -p "Polybar" -bw 0 -lines 2 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
			if [ "$comptonconfig" = "Reload" ]; then
				killall compton && compton &
			elif [ $comptonconfig ]; then
				i3-msg exec $editor ~/.config/compton.conf
			fi
		;;
		'Rofi')
			roficonfig=$(echo "Apps;Config;Themes" | rofi -theme "$tema" -sep ";" -dmenu -p "Rofi" -bw 0 -lines 3 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)

			if [ "$roficonfig" = "Apps" ]; then
				app=$( ls "${HOME}/.config/rofi/" | rofi -theme "$tema" -dmenu -p "Rofi Apps" -bw 0 -lines 11 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
				if [ $app ]; then
					i3-msg exec $editor "${HOME}/.config/rofi/${app}"
				fi
			elif [ "$roficonfig" = "Themes" ]; then
				tema=$( ls "${HOME}/.config/rofi/" | rofi -theme "$tema" -dmenu -p "Rofi Apps" -bw 0 -lines 20 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
				if [ $tema ]; then
					i3-msg exec $editor "${HOME}/.config/rofi/${app}"
				fi
			elif [ $roficonfig ]; then
				i3-msg exec $editor ~/.config/rofi/relaxDrun.rasi
			fi
		;;
		'LightDM')
			ldm=$(echo "lightdm;lightdm-gtk-greeter" | rofi -theme "$tema" -sep ";" -dmenu -p "LightDM" -bw 0 -lines 2 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)

			if [ $ldm ]; then
				i3-msg exec sudo $editor "/etc/lightdm/${ldm}.conf"
			fi
		;;
		'ncmpcpp')
		    i3-msg exec $editor "${HOME}/.config/ncmpcpp/config"
		;;
		'qutebrowser') i3-msg exec $editor ~/.config/qutebrowser/config.py ;;
		'StartPage')
		    i3-msg exec $editor "${HOME}/.config/startpage/*.html"
		;;
		'Home')
			homefiles=$(echo ".Xresources;.xinitrc;.xprofile;.Xdefaults;.bashrc;.bash_aliases;.bash_profile;.vimrc;mimeapps;bin;.bin" | rofi -theme "$tema" -sep ";" -dmenu -p "Home Files" -bw 0 -lines 11 -separator-style none -location 0 -width 190 -hide-scrollbar -padding 5)

			if [ "$homefiles" = ".Xresources" ]; then
				resfiles=$( echo "Config;Cores" | rofi -theme "$tema" -sep ";" -dmenu -p "~/.Xresources" -bw 0 -lines 2 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
				if [ "$resfiles" == "Config" ]; then
					i3-msg exec $editor ~/.Xresources
				elif [ "$resfiles" == "Cores" ]; then
					colorfiles=$(ls "${HOME}/.colors/" | rofi -theme "$tema" -dmenu -p "Xresources Colors" -bw 0 -lines 10 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
					if [ $colorfiles ]; then
						i3-msg exec $editor ~/.colors/${colorfiles}
					fi
				fi
			elif [ "$homefiles" = "bin" ]; then
				binfiles=$(ls "${HOME}/bin/" | rofi -theme "$tema" -dmenu -p "~/bin" -bw 0 -lines 10 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
				if [ $binfiles ]; then
					i3-msg exec $editor ~/bin/${binfiles}
				fi
            elif [ "$homefiles" = ".bin" ]; then
				dotbinfiles=$(ls "${HOME}/.local/bin/" | rofi -theme "$tema" -dmenu -p "~/.local/bin" -bw 0 -lines 11 -separator-style none -location 0 -width 400 -hide-scrollbar -padding 5)
				if [ $dotbinfiles ]; then
					i3-msg exec $editor ~/.local/bin/${dotbinfiles}
				fi
			elif [ "$homefiles" = "mimeapps" ]; then
				i3-msg exec $editor ~/.config/mimeapps.list
			elif [ $homefiles ]; then
				i3-msg exec $editor ~/${homefiles}
			fi
		;;
	esac
fi
