#!/bin/bash

bspc monitor -d term code browser settings midia music others
"$HOME"/.config/polybar/launch.sh &

sxhkd &

timedatectl set-timezone America/Sao_Paulo

picom &&

setxkbmap -model abnt2 -layout br -variant abnt2

wmname LG3D

# -----------------------------------------
# bspwm config
# -----------------------------------------
bspc config window_gap          2
bspc config border_width        0
bspc config pointer_follows_focus false
bspc config top_padding  5
bspc config bottom_padding 30
# bspc config focus_follows_pointer true

bspc config split_ratio               0.52
bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config history_aware_focus       true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config click_to_focus            true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
#------------------------------------------------
# Border Colors
#------------------------------------------------
bspc config focused_border_color         "#F6F9FF"
bspc config active_border_color          "#F6F9FF"
# bspc config normal_border_color          "#34322E"
bspc config presel_border_color          "#F6F9FF"
bspc config focused_locked_border_color  "#CFB776"
bspc config active_locked_border_color   "#F6F9FF"
bspc config normal_locked_border_color   "#34322E"
bspc config focused_sticky_border_color  "#E3A5DA"
bspc config active_sticky_border_color   "#F6F9FF"
bspc config normal_sticky_border_color   "#34322E"
bspc config focused_private_border_color "#42CAD9"
bspc config active_private_border_color  "#F6F9FF"
bspc config normal_private_border_color  "#34322E"
bspc config urgent_border_color          "#F9A299"



#──────────────────────────────────
# ────────────── Rules ──────────────
#──────────────────────────────────
# bspc rule -a Firefox desktop=^'2' state=tiled follow=on
# bspc rule -a Thunar desktop=^'4' state=tiled follow=on
# bspc rule -a URxvt desktop=^'1' state=tiled follow=on
# bspc rule -a Subl3 desktop='^5' state=tiled follow=on
# bspc rule -a Pavucontrol desktop='^3' state=floating follow=on
# bspc rule -a Code desktop=^'5' state=tiled follow=on
# bspc rule -a Nitrogen desktop=^'2' state=floating follow=on
# bspc rule -a Opera desktop=^'2' state=tiled follow=on
# bspc rule -a Telegram desktop=^'6' state=floating follow=on
# bspc rule -a Lxappearance desktop=^'1' state=floating follow=on
# bspc rule -a burp-StartBurp desktop=^'3' state=tiled follow=on
# bspc rule -a Wireshark desktop=^'3' state=tiled follow=on
# bspc rule -a Code desktop=^'5' follow=on state=tiled
# bspc rule -a VirtualBox desktop=^'3' state=tiled follow=on
# bspc rule -a Termite desktop=^'2' state=floating follow=on
# bspc rule -a Alacritty desktop=^'2' state=floating follow=on
# bspc rule -a Nautilus desktop=^'4' state=tiled follow=on
# bspc rule -a Pulseeffects desktop=^'3' state=floating follow=off
# bspc rule -a Atom desktop=^'5' state=tiled follow=on
# bspc rule -a code desktop=^'5' state=tiled follow=on
# bspc rule -a hyper desktop=^'1' state=floating follow=off
#bspc rule -a
#bspc rule -a URxvt:ncmpcpp desktop=^8
